'use client'

import { useEffect } from 'react'
import './globals.css'
import type { Metadata } from 'next'

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    const handleRouteChange = () => {
      const iframeHeight = document.body.scrollHeight
      window.parent.postMessage({ type: 'iframeHeight', height: iframeHeight }, '*')
    };

    handleRouteChange()

    const observer = new MutationObserver(handleRouteChange)

    observer.observe(document.body, { attributes: true, childList: true, subtree: true })
    return () => {
      observer.disconnect()
    }

  }, [])

  return (
    <html lang="en">
      <body className="font-light max-w-[1100px]">
        {children}
      </body>
    </html>
  )
}
